var sqlMap = {
    user: {
        seachUser: 'select id,email,name,roleId from users where email = ? and password = ? and state = 1',
        userList: 'select users.*,roles.roleName from users,roles where users.roleId = roles.id',
        addUser: 'insert into users (name,password,email,iphone,roleId,state,create_time) values (?,?,?,?,2,?,?)',
        getUserById:'select * from users where id = ?',
        editUser: 'update users set price = ?, commission = ?, state = ? where id = ?',
        removeUserById: 'delete from users where id = ?',
        getRoles: 'select * from roles',
        editUserRole: 'update users set roleId = ? where id = ?'
    },
    power: {
        getRightList: 'select * from rights ORDER BY level ASC',
        getRoleList: 'select roles.id,roles.roleName,roles.roleDesc,rights.authName,rights.path,(rights.id)as rightId,rights.rights_id from rights,roles WHERE find_in_set(rights.id,roles.rightsId)',
        removeRoleById: 'delete from roles where id = ?',
        addRole: "insert into roles (roleName, roleDesc, rightsId) values (?, ?, '1')",
        getAllRights: 'select * from rights ORDER BY level ASC',
        portionRight: 'update roles set rightsId = ? where id = ?'
    },
    regular: {
        addRegular: 'insert into regulars (regName) values (?)',
        geetRegularTotal: 'select count(*) from regulars',
        getRegularList: 'select * from regulars ORDER BY id DESC',
        editRegular: 'update regulars set regName = ? where id = ?',
        removeRegular: 'delete from regulars where id = ?',
        addSpendDay: 'insert into spendday (regId, cost, cerateTime) values (?, ?, ?)',
        getSpendDayTotal: 'select count(*) from spendday',
        getSpendDayList: 'select spendday.*,regulars.regName from spendday,regulars where spendday.regId = regulars.id ORDER BY spendday.id DESC LIMIT ? , ?',
        removeSpendDay: 'delete from spendday where id = ?',
        getSpendDayById: 'select id,cost from spendday where id = ?',
        editSpendDayCost: 'update spendday set cost = ? where id = ?',
        addTool: 'insert into tools (toolName) values (?)',
        getToolTotal: 'select count(*) from tools',
        getToolList: 'select * from tools ORDER BY id DESC LIMIT ? , ?',
        removeTool: 'delete from tools where id = ?',
        editTool: 'update tools set toolName = ? where id = ?',
        getTools: 'select * from tools',
        seachToolCost: 'select toolcost.*,tools.toolName,users.name from toolcost,tools,users where toolcost.toolId = tools.id and toolcost.userId = users.id and toolcost.cerateTime > ? and toolcost.cerateTime < ? ORDER BY toolcost.id DESC',
        seachToolIdToolCost: 'select toolcost.*,tools.toolName,users.name from toolcost,tools,users where toolcost.toolId = tools.id and toolcost.userId = users.id and toolcost.toolId = ? and toolcost.cerateTime > ? and toolcost.cerateTime < ? ORDER BY toolcost.id DESC',
        addToolCost: 'insert into toolcost (userId, toolId, toolCost, cerateTime) values (?, ?, ?, ?)',
        getToolCostTotal: 'select count(*) from toolcost',
        getToolCostList: 'select toolcost.*,tools.toolName,users.name from toolcost,tools,users where toolcost.toolId = tools.id and toolcost.userId = users.id ORDER BY toolcost.id DESC LIMIT ? , ?',
        removeToolCost: 'delete from toolcost where id = ?',
        getToolCostById: 'select id,toolCost from toolcost where id = ?',
        editToolCost: 'update toolcost set toolCost = ? where id = ?',
        addAdvertisers: 'insert into advertisers (adName, cerateTime) values (?, ?)',
        getAdvertiserstotal: 'select count(*) from advertisers',
        getAdvertisers: 'select * from advertisers ORDER BY id DESC LIMIT ? , ?',
        removeAd: 'delete from advertisers where id = ?',
        getUserList: 'select * from users where state = 1',
        getAdList: 'select id,adName from advertisers',
        addAdCost: 'insert into adcost (userId, adId, accountCost, adCost, formalities, cerateTime) values (?, ?, ?, ?, ?, ?)',
        getAdCostTotal: 'select count(*) from adcost',
        getAdCostList: 'select adcost.*,users.name,advertisers.adName,(adcost.accountCost+(1+adcost.formalities)*adcost.adCost) as total from adcost,users,advertisers where adcost.userId = users.id and adcost.adId = advertisers.id ORDER BY adcost.id DESC LIMIT ? , ?',
        seachTimeAdCost: 'select adcost.*,users.name,advertisers.adName,(adcost.accountCost+(1+adcost.formalities)*adcost.adCost) as total from adcost,users,advertisers where adcost.userId = users.id and adcost.adId = advertisers.id and adcost.cerateTime > ? and adcost.cerateTime < ? ORDER BY adcost.id DESC',
        seachUserIdAdCost: 'select adcost.*,users.name,advertisers.adName,(adcost.accountCost+(1+adcost.formalities)*adcost.adCost) as total from adcost,users,advertisers where adcost.adId = advertisers.id and users.id = ? and adcost.userId = ? and adcost.cerateTime > ? and adcost.cerateTime < ? ORDER BY adcost.id DESC',
        seachAdIdAdCost: 'select adcost.*,users.name,advertisers.adName,(adcost.accountCost+(1+adcost.formalities)*adcost.adCost) as total from adcost,users,advertisers where adcost.adId = advertisers.id and users.id = adcost.userId and adcost.adId = ? and adcost.cerateTime > ? and adcost.cerateTime < ? ORDER BY adcost.id DESC',
        seachUsuerAdIdAdCost: 'select adcost.*,users.name,advertisers.adName,(adcost.accountCost+(1+adcost.formalities)*adcost.adCost) as total from adcost,users,advertisers where adcost.adId = advertisers.id and users.id = ? and adcost.userId = ? and adcost.adId = ? and adcost.cerateTime > ? and adcost.cerateTime < ? ORDER BY adcost.id DESC',
        removeAdCost: 'delete from adcost where id = ?',
        getAdCostById: 'select id, accountCost, adCost, formalities from adcost where id = ?',
        editAdCost: 'update adcost set accountCost = ?, adCost = ?, formalities = ? where id = ?',
        addNetAlliances: 'insert into netalliances (naName, cerateTime) values (?, ?)',
        getNetAlliancestotal: 'select count(*) from netalliances',
        getNetAlliances: 'select * from netalliances ORDER BY id DESC LIMIT ? , ?',
        removeNa: 'delete from netalliances where id = ?',
        getNetAlliance: 'select * from netalliances',
        addNaMoney: 'insert into netalliancemoney (userId, naId, remitMoney, cerateTime) values (?, ?, ?, ?)',
        getNaMoneyTotal: 'select count(*) from netalliancemoney',
        getNaMoneyList: 'select netalliancemoney.*,netalliances.naName,users.name from netalliancemoney,netalliances,users where netalliancemoney.naId = netalliances.id and netalliancemoney.userId = users.id ORDER BY netalliancemoney.id DESC LIMIT ? , ?',
        getNaMoneyById: 'select id,remitMoney from netalliancemoney where id = ?',
        saveNaMoney: 'update netalliancemoney set remitMoney = ? where id = ?',
        removeNaMoney: 'delete from netalliancemoney where id = ?',
        seachTimeNamoney: 'select netalliancemoney.*,netalliances.naName,users.name from netalliancemoney,netalliances,users where netalliancemoney.naId = netalliances.id and netalliancemoney.userId = users.id and netalliancemoney.cerateTime > ? and netalliancemoney.cerateTime < ? ORDER BY netalliancemoney.id DESC ',
        seachUserIdNamoney: 'select netalliancemoney.*,netalliances.naName,users.name from netalliancemoney,netalliances,users where netalliancemoney.naId = netalliances.id and users.id = netalliancemoney.userId and netalliancemoney.userId = ? and netalliancemoney.cerateTime > ? and netalliancemoney.cerateTime < ? ORDER BY netalliancemoney.id DESC ',
        seachNaIdNamoney: 'select netalliancemoney.*,netalliances.naName,users.name from netalliancemoney,netalliances,users where netalliancemoney.naId = netalliances.id and netalliancemoney.userId = users.id and netalliancemoney.naId = ? and netalliancemoney.cerateTime > ? and netalliancemoney.cerateTime < ? ORDER BY netalliancemoney.id DESC ',
        seachUserIdNaId: 'select netalliancemoney.*,netalliances.naName,users.name from netalliancemoney,netalliances,users where netalliancemoney.naId = netalliances.id and users.id = netalliancemoney.userId and netalliancemoney.userId = ? and netalliancemoney.naId = ? and netalliancemoney.cerateTime > ? and netalliancemoney.cerateTime < ? ORDER BY netalliancemoney.id DESC ',
        addAccountCost: 'insert into accountcost (userId, accountCost, msg, cerateTime) values (?, ?, ?, ?)',
        getAccountCostTotal: 'select count(*) from accountcost',
        getAccountCostList: 'select accountcost.*,users.name from accountcost,users where accountcost.userId = users.id ORDER BY accountcost.id DESC LIMIT ? , ?',
        seachTimeAccountCost: 'select accountcost.*,users.name from accountcost,users where accountcost.userId = users.id and accountcost.cerateTime > ? and accountcost.cerateTime < ? ORDER BY accountcost.id DESC',
        seachUserAccountCost: 'select accountcost.*,users.name from accountcost,users where accountcost.userId = users.id and accountcost.userId = ? and accountcost.cerateTime > ? and accountcost.cerateTime < ? ORDER BY accountcost.id DESC',
        removeAccountCost: 'delete from accountcost where id = ?',
        getAccountCostById: 'select id,accountCost,msg from accountcost where id = ?',
        editAccountCost: 'update accountcost set accountCost = ?, msg = ? where id = ?',
        addCommission: 'insert into commission (userId, commission, month, cerateTime) values (?, ?, ?, ?)',
        getCommissionTotal: 'select count(*) from commission',
        getCommissionList: 'select commission.*,users.name from commission,users where commission.userId = users.id ORDER BY commission.id DESC LIMIT ? , ?',
        removeCommission: 'delete from commission where id = ?',
        addExchage: 'insert into exchange (RMB_USD, USD_RMB, month, cerateTime) values (?, ?, ?, ?)',
        getExchangeList: 'select * from exchange ORDER BY id DESC',
        removeExchange: 'delete from exchange where id = ?',
        addPublic: 'insert into public (naId, publicMoney, msg, cerateTime) values (?, ?, ?, ?)',
        getPublicTotal: 'select count(*) from public',
        getPublicList: 'select public.*,netalliances.naName from public,netalliances where public.naId = netalliances.id ORDER BY public.id DESC LIMIT ? , ?',
        getPublicById: 'select * from public where id = ?',
        saveEditPublic: 'update public set naId = ?, publicMoney = ?, msg = ? where id = ?',
        removePublic: 'delete from public where id = ?',
        seachTimePublic: 'select public.*,netalliances.naName from public,netalliances where public.naId = netalliances.id and public.cerateTime > ? and public.cerateTime < ? ORDER BY public.id DESC',
        seachNaIdPublic: 'select public.*,netalliances.naName from public,netalliances where public.naId = netalliances.id and public.naId = ? and public.cerateTime > ? and public.cerateTime < ? ORDER BY public.id DESC',
        getProfitToolCost: `SELECT FROM_UNIXTIME(cerateTime,'%d') as date,sum(toolCost) as toolCost FROM toolcost WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m') GROUP BY date`,
        getProfitNaMoney: `SELECT FROM_UNIXTIME(cerateTime,'%d') as date,sum(remitMoney) as remitMoney FROM netalliancemoney WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m') GROUP BY date`,
        getProfitpublicMoney: `SELECT FROM_UNIXTIME(cerateTime,'%d') as date,sum(publicMoney) as publicMoney FROM public WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m') GROUP BY date`,
        getProfitAdCost: `SELECT FROM_UNIXTIME(cerateTime,'%d') as date,sum(accountCost+adCost*(1+formalities)) as adCost FROM adcost WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m') GROUP BY date`,
        addTransform: 'insert into transform (userId, number, cerateTime) values (?, ?, ?)',
        getTransformTotal: 'select count(*) from transform',
        getTransformList: 'select transform.*,users.name from transform,users where transform.userId = users.id ORDER BY transform.id DESC LIMIT ? , ?',
        seachTimeTransform: 'select transform.*,users.name from transform,users where transform.userId = users.id and transform.cerateTime > ? and transform.cerateTime < ? ORDER BY transform.id DESC',
        seachUserTransform: 'select transform.*,users.name from transform,users where transform.userId = users.id and transform.userId = ? and transform.cerateTime > ? and transform.cerateTime < ? ORDER BY transform.id DESC',
        removeTransform: 'delete from transform where id = ?',
        getRoiAdCost: `SELECT FROM_UNIXTIME(cerateTime,'%d') as date,sum(accountCost+adCost*(1+formalities)) as adCost FROM adcost WHERE userId = ? and FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m') GROUP BY date`,
        getRoiAccountCost:`SELECT FROM_UNIXTIME(cerateTime,'%d') as date,sum(accountCost) as accountCost FROM accountcost WHERE userId = ? and FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m') GROUP BY date`,
        getRoiNumber: `SELECT FROM_UNIXTIME(cerateTime,'%d') as date,sum(number) as number FROM transform WHERE userId = ? and FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m') GROUP BY date`,
        getRoiNaMoney: `SELECT FROM_UNIXTIME(cerateTime,'%d') as date,sum(remitMoney) as NaMoney FROM netalliancemoney WHERE userId = ? and FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m') GROUP BY date`,
        getMonthDomain: `SELECT FROM_UNIXTIME(cerateTime,'%d') as date,sum(price) as domainPrice FROM domains WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m') GROUP BY date`,
        getAdRevenueAdCost: `SELECT FROM_UNIXTIME(cerateTime,'%d') as date,sum(accountCost+adCost*(1+formalities)) as adCost FROM adcost WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m') GROUP BY date`,
        getBlitzAdsGroupList: `SELECT FROM_UNIXTIME(cerateTime,'%d') as date,sum(remitMoney) as remitMoney FROM netalliancemoney WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m') and naId = ? GROUP BY date`,
        getMergeProfit: `
        SELECT 
        sum(remitMoney) as remitMoney,
       (SELECT sum(toolCost) FROM toolcost WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m')) as toolCost,
       (SELECT SUM(adCost) FROM adcost WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m')) as adCost,
       (SELECT SUM(cost) FROM spendday WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m')) as rcCost,
       (SELECT sum(price) FROM domains WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m')) as domainPrice,
       (select RMB_USD from exchange WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(month,'%Y-%m')) as RMB_USD
    FROM netalliancemoney WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m')
        `,
        getPay: `SELECT 
                    users.name,
                    users.price,
                    commission.commission,
                    (SELECT sum(remitMoney) FROM netalliancemoney WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m')) as naMoney,
                    (SELECT sum(toolCost) FROM toolcost WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m')) as toolCost,
                    (SELECT SUM(adCost) FROM adcost WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m')) as adCost,
                    (SELECT SUM(cost) FROM spendday WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m')) as rcCost,
                    (SELECT sum(price) FROM domains WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(cerateTime,'%Y-%m')) as domainPrice,
                    (select RMB_USD from exchange WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(month,'%Y-%m')) as RMB_USD,
                    (select USD_RMB from exchange WHERE FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(month,'%Y-%m')) as USD_RMB
                FROM users,commission where users.id = commission.userId and users.roleId = 4 AND (FROM_UNIXTIME(?,'%Y-%m') = FROM_UNIXTIME(commission.cerateTime,'%Y-%m'))`,
        seachPerbalance: `select balance FROM money ORDER BY id DESC LIMIT 0,1`,    
        addMoney: 'insert into money (userId, price, balance, msg, type, cerateTime) values (?, ?, ?, ?, ?, ?)',
        outMoney: 'insert into money (userId, price, balance, msg, type, cerateTime) values (?, ?, ?, ?, ?, ?)',
        getMoney: 'select money.*,users.name from money,users where money.userId = users.id ORDER BY id DESC LIMIT 0,50',
        outToolMoney: 'insert into money (userId, price, balance, msg, type, cerateTime) values (?, ?, ?, ?, ?, ?)',
        seachMoney: 'select money.*,users.name from money,users where money.userId = users.id and money.cerateTime > ? and money.cerateTime < ? ORDER BY id DESC'
    },
    domain: {
        getUserList: 'select id,name from users where state = 1',
        addDmoain: 'insert into domains (userId, domain, price, cerateTime) values (?, ?, ?, ?)',
        domainTotal: 'select count(*) from domains',
        domainList: 'select domains.*,users.name from domains,users where domains.userId = users.id ORDER BY domains.id DESC LIMIT ? , ?'
    },
    home: {
        getMenuList: 'select * from rights'
    }
}

module.exports = sqlMap